AWSTemplateFormatVersion: "2010-09-09"
Description: Cafe application layer (EC2 + SG + IAM)

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  CafeNetworkParameter:
    Type: String
    Default: cafe-network
    Description: Name of the network stack to import values from
  InstanceTypeParameter:
    Type: String
    Description: Choose EC2 instance type
    Default: t2.small
    AllowedValues: [t2.micro, t2.small, t3.micro, t3.small]

Mappings:
  RegionMap:
    ap-northeast-1: { keypair: vockey }

Resources:
  CafeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess

  CafeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ !Ref CafeRole ]

  CafeSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Cafe web server
      VpcId:
        Fn::ImportValue: !Sub '${CafeNetworkParameter}-VpcID'
      SecurityGroupIngress:
        - { IpProtocol: tcp, FromPort: 80, ToPort: 80, CidrIp: 0.0.0.0/0 }
        - { IpProtocol: tcp, FromPort: 22, ToPort: 22, CidrIp: 0.0.0.0/0 }
      Tags: [ { Key: Name, Value: Cafe SG } ]

  CafeInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !FindInMap [RegionMap, !Ref "AWS::Region", keypair]
      IamInstanceProfile: !Ref CafeInstanceProfile
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          SubnetId:
            Fn::ImportValue: !Sub '${CafeNetworkParameter}-SubnetID'
          GroupSet: [ !Ref CafeSG ]
      Tags: [ { Key: Name, Value: Cafe Web Server } ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum -y update
          yum install -y httpd mariadb-server wget
          amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
          systemctl enable httpd && systemctl start httpd
          systemctl enable mariadb && systemctl start mariadb
          wget https://aws-tc-largeobjects.s3.us-west-2.amazonaws.com/CUR-TF-200-ACACAD-2-91555/14-lab-mod10-challenge-CFn/s3/cafe-app.sh
          chmod +x cafe-app.sh && ./cafe-app.sh

Outputs:
  WebServerPublicIP:
    Description: Public IPv4 of the Cafe web server
    Value: !GetAtt CafeInstance.PublicIp
